spring.application.name=demo2

server.port = 8080

#server.port=443
#server.ssl.key-store=classpath:/sslKey/sslKey.p12
#server.ssl.key-store-password=aassddffgg11$$
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=tomcat

# servlet의 접두사와 접미사
#spring.mvc.view.prefix=/WEB-INF/view/
#spring.mvc.view.suffix=.jsp

# 재부팅 없이 정적 뷰 파일 바로 반영
spring.devtools.livereload.enabled=true

# thymeleaf view 위치
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# thymeleaf 캐시를 남기지 않음 -> 즉각 반영
spring.thymeleaf.cache=false

# HTML 모드
spring.thymeleaf.mode=HTML

# 디렉토리에 파일이 없으면 에러 발생
spring.thymeleaf.check-template-location=true

# 인코딩
spring.thymeleaf.encoding=UTF-8
#https://adjh54.tistory.com/75#3.%C2%A0%20%ED%8C%8C%EC%9D%BC%20%EA%B5%AC%EC%84%B1%201%20-%20Header%20Layout-1-9





# RDB 중 연결할 DB 엔진에 대한 드라이브 설정
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/egov
#spring.datasource.url=jdbc:mysql://localhost:3306/soulinku
spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/soulinku
spring.datasource.username=soulinku
spring.datasource.password=aassddffgg11$$


# MyBatis
#mybatis.type-aliases-package=com.soulinku.demo2.dto
#mybatis.mapper-locations=classpath:mapper/**/*.xml
#mybatis.config-location=classpath:mybatis-config.xml
#mybatis.configuration.map-underscore-to-camel-case=true
#spring.datasource.sql-script-encoding=UTF-8




